version: '3'
services:
  test:
    build: .
    ports:
      - "3000"
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BULLET: enabled
      RAILS_ENV: test
      RACK_ENV: test
      PORT: 3000
      SECRET: keyboard cat
      WAIT_HOSTS: postgres:5432
    container_name: prep-api-test
    command: test
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.2
    container_name: prep-db-test
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prep_test



