version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "$HOME/tmp/prep-manager/postgres:/var/lib/postgresql"
  web:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      - RACK_ENV=development
      - RAILS_ENV=development
      - PORT=4000
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - POSTGRES_USER=postgres
    restart: always
    container_name: prep-manager
    volumes:
      - "$HOME/tmp/prep-manager/uploads:/usr/src/prep-manager/public/system"
      - "./:/usr/src/prep-manager"
    depends_on:
      - db
    links:
      - db
