version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - PORT=4000
    restart: always
    container_name: prep-manager
    volumes:
      - "/home/ubuntu/prep-manager/uploads:/usr/src/prep-manager/public/system"
