apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prep
  labels:
    name: {name}-preproduction
  name: {name}-preproduction
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}-preproduction
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "webapps"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - {name}-preproduction
              topologyKey: kubernetes.io/hostname

      containers:
      - name: {name}-preproduction
        image: vizzuality/{name}
        imagePullPolicy: Always
        args:
          - start
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: APIGATEWAY_URL
            value: http://production-api.globalforestwatch.org
          - name: AUTH_USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: PREP_MANAGER_AUTH_USERNAME
          - name: AUTH_PASSWORD
            valueFrom:
                SecretKeyRef:
                  name: appsecrets
                  key: PREP_MANAGER_AUTH_PASSWORD
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: PREP_MANAGER_POSTGRES_URL
          - name: S3_BUCKET_NAME
            value: "wri-api-backups"
          - name: S3_PATH
            value: "prep/production"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_SECRET_ACCESS_KEY


        ports:
          - containerPort: 3000

      restartPolicy: Always
