apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        env:
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RW_API_URL
            value: https://api.resourcewatch.org/v1
          - name: APIGATEWAY_URL
            value: http://production-api.globalforestwatch.org
          - name: AUTH_USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: PREP_MANAGER_AUTH_USERNAME
          - name: AUTH_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: PREP_MANAGER_AUTH_PASSWORD
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: PREP_MANAGER_POSTGRES_URL
          - name: S3_BUCKET_NAME
            value: "wri-api-backups"
          - name: S3_PATH
            value: "prep/staging"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_SECRET_ACCESS_KEY

        ports:
          - containerPort: 3000

      restartPolicy: Always
