apiVersion: v1
kind: Service
metadata:
  namespace: prep
  labels:
    name: prep-api-staging
  name: prep-api-staging
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: prep-api-staging
